version: '3' 

services: 
    simple-web-service:  
      image: devopsdockeruh/simple-web-service
 #     build: .
      volumes: 
        - /home/zbook/docker-part2/2.1/text.log:/usr/src/app/text.log
      container_name: simplews
