version: '3' 

services: 
    frontend:  
      container_name: frontend
      build: fe/
      ports:
        - 5000:5000
    backend:  
      container_name: backend
      build: be/
      ports:
        - 8080:8080
    redis:
      image: redis:6
      container_name: redis
#      ports:
#        - 6379:6379
      
    
