version: '3' 

services: 
    postgres:
      container_name: postgres
      image: postgres
      restart: unless-stopped
      environment:
        POSTGRES_PASSWORD: postgres
        POSTGRES_USER: postgres
        POSTGRES_DB: postgres
      volumes:
        - database:/var/lib/postgresql/data

    frontend:  
      container_name: frontend
      build: fe/
      ports:
        - 5000:5000

    backend:  
      container_name: backend
      build: be/
      ports:
        - 8080:8080
      environment:
        POSTGRES_PASSWORD: postgres
        POSTGRES_USER: postgres
        POSTGRES_DATABASE: postgres
        POSTGRES_HOST: postgres
      depends_on: 
        - postgres

    redis:
      image: redis:6
      container_name: redis

volumes:
  database: